server:
  port: 8081

logging:
  level:
    root: warn
    com.lrm: debug
  file:
    name: logs/debug.log

spring:
  datasource:
    url: jdbc:mariadb://your-domain:3306/your-table?useUnicode=true&characterEncoding=utf-8
    username: your-username
    password: your-password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
  resources:
    static-locations: classpath:/static/
    cache-period: 0
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
